networks:
  app-network:
    driver: bridge

services:
  interface:
    build:
      context: ./interface
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    volumes:
      - ./interface:/app/interface
      - ./.env:/app/interface/.env
      - interface_node_modules:/app/interface/node_modules
    depends_on:
      api:
        condition: service_started
    environment:
      - VITE_API_URL=http://localhost:8080
      - NODE_ENV=development

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    volumes:
      - ./api:/app/api
      - ./.env:/app/api/.env
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      db-container-chega-facil:
        condition: service_started
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://userroot:Root4523@db-container-chega-facil:5432/chega-facil-database

  # Serviço de banco de dados (PostgreSQL)
  db-container-chega-facil:
    container_name: postgres-chega-facil
    image: postgres:14
    restart: always
    ports:
      - "4523:5432"
    environment:
      - POSTGRES_USER=userroot
      - POSTGRES_PASSWORD=Root4523
      - POSTGRES_DB=chega-facil-database
      - PGUSER=userroot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U userroot -d chega-facil-database"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:
    name: chega-facil-postgres-data
  interface_node_modules: