services:
  # interface:
  #   build:
  #     context: ./interface
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:3000"
  #   volumes:
  #     - ./interface:/app
  #     - /app/node_modules
  #   depends_on:
  #     - api
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:8080

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - db-container-chega-facil
    environment:
      - DATABASE_URL=postgresql://rootuser:Root5432@db-container-chega-facil:4523/chega-facil-database
      - NODE_ENV=development

  db-container-chega-facil:
    container_name: postgres-chega-facil
    image: postgres:14
    restart: always
    ports:
      - "4523:5432"
    environment:
      - POSTGRES_USER=userroot
      - POSTGRES_PASSWORD=Root4523
      - POSTGRES_DB=chega-facil-database
      - PGUSER=userroot
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: chega-facil-postgres-data